# Setup
title: Probing Tokens
tagline: "Probing Tokens Online"
description: "A sandbox to present some of the results of probing tokens online."
url: https://probingtokens.online/
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Behnam Baharmand
  url: https://www.baharmand.com
  email: behnum@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
